using Google.Protobuf.Reflection;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class GameController : MonoBehaviour
{
    private LevelGeneration _levelGenerationScript;
    private TileManager _tileManagerScript;
    private GameObject _agent;
    private Vector3Int tilemapOrigin;

    public GameObject smallAgentPrefab;
    public GameObject mediumAgentPrefab;
    public GameObject largeAgentPrefab;
    public PlayerManager playerManagerScript;
    public static GameController instance = null;

    public bool shouldGenerateLevel;

    // Signaling a new level should be generated
    public static event Action<LevelInfoScriptableObject.BaseType> OnGenerateLevel;
    public static event Action<List<Vector3>, Vector3> OnSpawnEnemies;

    // Subscribing to the LevelGenerated event
    private void OnEnable()
    {
        LevelGeneratorAgent.OnLevelGenerated += HandleLevelGenerated;
    }

    // Unsubscribing from the LevelGenerated event
    private void OnDisable()
    {
        LevelGeneratorAgent.OnLevelGenerated -= HandleLevelGenerated;
    }

    private void Awake()
    {
        if (instance == null) { instance = this; }
        else if (instance != this) { Destroy(instance); }

        // keep gamemanager for all scenes
        DontDestroyOnLoad(gameObject);

        playerManagerScript = GetComponent<PlayerManager>();
    }

    // Start is called before the first frame update
    void Start()
    {
        intializeLevel();
    }

    // Update is called once per frame
    void Update()
    {

    }

    private void intializeLevel()
    {
        /// Logic to vary level sizes depending of how many levels the player completed
        LevelInfoScriptableObject.BaseType desiredBaseType = LevelInfoScriptableObject.BaseType.Large;

        // instanciate agent according to the baseType
        GameObject agentPrefab = null;
        switch (desiredBaseType)
        {
            case LevelInfoScriptableObject.BaseType.Small:
                agentPrefab = smallAgentPrefab;
                break;
            case LevelInfoScriptableObject.BaseType.Medium:
                agentPrefab = mediumAgentPrefab;
                break;
            case LevelInfoScriptableObject.BaseType.Large:
                agentPrefab = largeAgentPrefab;
                break;
            default:
                Debug.LogError("Unsupported BaseType");
                return;
        }

        _agent = Instantiate(agentPrefab);
        UpdateShouldGenerateLevel();

        _levelGenerationScript = _agent.GetComponent<LevelGeneration>();
        _tileManagerScript = _agent.GetComponent<TileManager>();

        Debug.Log("GAME CONTROLLER: shouldGenerateLevel " + shouldGenerateLevel);

        if (shouldGenerateLevel)
        {
            GenerateLevel(desiredBaseType);
            UpdateShouldGenerateLevel();
        }
    }
    // Handle the event when a level is generated
    private void HandleLevelGenerated()
    {
        Debug.Log("Level is generated. Proceed with the game flow.");
        UpdateShouldGenerateLevel();
        if (!shouldGenerateLevel)
        {

            // convert Tilemap positions into World positions
            List<Vector3> spawnPositions = TileMapToWorldPosition(_tileManagerScript.SpawnLocations);

            // spawn player inside the level
            playerManagerScript.SpawnPlayer(spawnPositions[0]);

            List<Vector3> floorPositions = TileMapToWorldPosition(_tileManagerScript.FloorLocations);
            SpawnEnemies(floorPositions);
        }
        else
        {
            Debug.LogWarning("GAME CONTROLLER: Generated Level was not playable! Regenerating Level");
            Destroy(_agent);
            Debug.LogWarning("GAME CONTROLLER: leftover agent was destroyed");
            intializeLevel();
        }
    }

    private void GenerateLevel(LevelInfoScriptableObject.BaseType baseType)
    {
        // Trigger the event with the desired base type
        Debug.Log("GAME CONTROLLER: Level should get generated by the Agent");
        OnGenerateLevel?.Invoke(baseType);
    }

    private void SpawnEnemies(List<Vector3> locations)
    {
        Debug.Log("GAME CONTROLLER: Enemies shoud get spawned");
        Vector3 playerPos = playerManagerScript.GetPlayerPosition();
        OnSpawnEnemies?.Invoke(locations, playerPos);
    }

    private List<Vector3> TileMapToWorldPosition(List<Vector2Int> locations)
    {
        List<Vector3> worldPositions = new List<Vector3>();
        tilemapOrigin = _levelGenerationScript.GetTilemapOrigin;

        foreach (var position in locations)
        {
            worldPositions.Add(new Vector3(tilemapOrigin.x + 0.5f + position.x, tilemapOrigin.y + 0.5f + position.y, 0));
        }

        return worldPositions;
    }

    private void UpdateShouldGenerateLevel()
    {
        shouldGenerateLevel = LevelGeneratorAgent.ShouldGenerateNewLevel;
    }
}
